name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install composer dependencies
        run: composer install --prefer-dist --ignore-platform-reqs

      - name: Run PHPUnit tests
        run: php bin/phpunit-8.4.3.phar --testsuite=unit

  build-functional:
    name: Functional tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install composer dependencies
        run: composer install --prefer-dist --ignore-platform-reqs

      - name: Run PHPUnit tests
        run: php bin/phpunit-8.4.3.phar --testsuite=functional

  build-infection:
    name: Infection tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install composer dependencies
        run: composer install --prefer-dist --ignore-platform-reqs

      - name: Run Infection
        run: php bin/infection.phar  --min-msi=70 --show-mutations
