name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-unit:
    name: Unit tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: [ '7.4', '8.0', '8.1' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install composer dependencies
        run: composer install --prefer-dist --ignore-platform-reqs
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Run PHPUnit tests
        run: php bin/phpunit-8.4.3.phar --testsuite=unit
        with:
          php-version: ${{ matrix.php-versions }}

  build-functional:
    name: Functional tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install composer dependencies
        run: composer install --prefer-dist --ignore-platform-reqs

      - name: Run PHPUnit tests
        run: php bin/phpunit-8.4.3.phar --testsuite=functional

  build-infection:
    name: Infection tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install composer dependencies
        run: composer install --prefer-dist --ignore-platform-reqs

      - name: Run Infection
        run: php bin/infection.phar  --min-msi=70 --show-mutations
